### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by RF-Dante** [kkapuria3/BestBuy-GPU-Bot#1]
Works well for me on testing!
I have one input if sounds good to you, after 2nd time ATC is clicked, it can try directly one of 2 URLS:
bestbuy.com/checkout/r/fast-track
bestbuy.com/checkout/r/fulfillment

**Comment by kkapuria3** [comment]
Hi @RF-Dante , 

With recent v2.5 update, carting time has been optimized. Best buy now also asks for verification if your login session token is expired. I am closing this issue until there's more interest.
