### ISSUE TITLE
Program Stuck in Initializing?

### ISSUE THREAD

**Issue by Toaster-Cat** [kkapuria3/BestBuy-GPU-Bot#10]
I'm new to get hub and this sort of thing, but recently my bot has been stuck in Initializing.  I've tried closing and reopening the window, signing in and out of my BB account, and re starting the script from the ground up but nothing seems to work...  It was working fine the first couple of days as well, but then just suddenly stopped.

**Comment by kkapuria3** [comment]
Did you try to delete the tampermonkey script and create a fresh copy  ?

**Comment by kkapuria3** [comment]
Please update the script. I have pushed the fix. There was a class name change for Out of Stock button.

**Comment by Toaster-Cat** [comment]
Awesome! works perfect now!
