### ISSUE TITLE
Stuck in Auto Detecting Mode

### ISSUE THREAD

**Issue by Lochos** [kkapuria3/BestBuy-GPU-Bot#16]
Hello, so I have been testing the bot using the AMD 5800x graphics card. I get this message: 

"Open Source BB-Bot V3.2 ◻️ TESTMODE: Yes ◻️ ITEM KEYWORD: 5800
Auto Detecting Mode
Initializing .."

However, it never adds it to my cart and I am not sure why not. Please let me know. Thanks!

**Comment by Lochos** [comment]
^^ I have tried with both Chrome and Firefox with popups enabled.

**Comment by kkapuria3** [comment]
What keyword are you using ? are you on the item page ?

**Comment by bennyalexluna** [comment]
hapenned to me too, using 3080, and Iam on the same page
ty

**Comment by kkapuria3** [comment]
Can you please join discord so I can support you with voice if needed ?

[![Discord](https://img.shields.io/discord/863863008329596968?color=%237289da%20&label=FOR%20SUPPORT%20AND%20FAQs%20%20%7C%20JOIN%20DISCORD&style=for-the-badge)](https://discord.gg/UcxcyxS5X8)

**Comment by bennyalexluna** [comment]
I will
Ty

**Comment by Lochos** [comment]
Joined 👌

**Comment by kkapuria3** [comment]
Please mention your issue in #general-help

**Comment by kkapuria3** [comment]
Pull request fixed this issue #17
