### ISSUE TITLE
CVV Bug

### ISSUE THREAD

**Issue by rnario85** [kkapuria3/BestBuy-GPU-Bot#18]
I think this section needs to be corrected. It errors out if the CVV field is not present. Also the first .value line is redundant.
Current:
        // CVV Number of Saved Card
        // Bug fix: by craz3drunner (discord member)
        document.getElementById("cvv").value = CREDITCARD_CVV;
        document.getElementById("cvv").focus();
        document.getElementById("cvv").select();
        if (!document.execCommand('insertText',false, CREDITCARD_CVV)) {
            document.getElementById("cvv").value = CREDITCARD_CVV;
        }

New:
        if(document.getElementById("cvv") != null) {
            document.getElementById("cvv").focus();
            document.getElementById("cvv").select();
            if (!document.execCommand('insertText',false, CREDITCARD_CVV)) {
                document.getElementById("cvv").value = CREDITCARD_CVV;
            }
        }

**Comment by kkapuria3** [comment]
I think this pull request should have solved this. If so, please close this issue @rnario85

**Comment by rnario85** [comment]
Fixed with latest update.
