### ISSUE TITLE
Window closes after first refresh when looking for out of stock items.

### ISSUE THREAD

**Issue by Drunkenrailer** [kkapuria3/BestBuy-GPU-Bot#25]
Every time I try to leave the bot running for an out of stock item it closes the tab. I let it sit for a minute or two after closing and nothing happens. I also tried running it in a separate window and the same thing happens. Did I do something wrong when setting up the bot that could have caused this?

**Comment by kkapuria3** [comment]
Do you have pop ups enabled for bestbuy.com ?

**Comment by Drunkenrailer** [comment]
Oh ok it works now. When I read to allow pop ups I thought just not having an ad blocker would be enough. I didn't know I had to manually enable them in chrome. This has fixed the issue, thank you very much.
