### ISSUE TITLE
Tab Keeps Closing

### ISSUE THREAD

**Issue by SovietComrade** [kkapuria3/BestBuy-GPU-Bot#27]
Tab keeps closing when it detects its out and tries to auto refresh. I filled out the red flags and put yes for test because I want to manually buy, I open the FE page on BB and then this issue occurs. Please help.

**Comment by kkapuria3** [comment]
have you enabled pop ups for BestBuy.com and refreshed your browser ?

**Comment by SovietComrade** [comment]
> have you enabled pop ups for BestBuy.com and refreshed your browser ?

I literally remembered after posting the question that you mentioned to enable pop ups. Sorry about that, thank you for the bot <3
