### ISSUE TITLE
Ended on review page without checking out

### ISSUE THREAD

**Issue by Hectorbeil** [kkapuria3/BestBuy-GPU-Bot#28]
I am running with Testmode = No, Cvv and sms filled in. When the item restocked, the page ended up on the leave a review page but the item was not purchased. The item was also not in cart.

**Comment by 15huangtimothy** [comment]
I also experience this same issue this morning when an item came in stock. Also noticed it seemed to open the leave a review page in a new tab and close the original tab with the listing, as I couldn't use the back button to get out.

**Comment by aprathna** [comment]
I've had the same issue here as well.

**Comment by SovietComrade** [comment]
Same here, it happened during both 3080 FE drops.

**Comment by TacitusSoldier** [comment]
Safe to assume everyone had this issue. It is weird that this is the first drop since using the bot that this issue popped up. BestBuy must have changed something with their drop system that caused this to occur.

**Comment by alexfinch7** [comment]
I can confirm that this happened again for today's drop.

Trying to find a fix. If anyone has one that would be appreciated.
