### ISSUE TITLE
Is there a way to limit a purchase to 1 with multiple tabs open?

### ISSUE THREAD

**Issue by swnotor** [kkapuria3/BestBuy-GPU-Bot#31]
As the title says, will i be able to run multiple tabs and have the script stop after checking out once?

**Comment by stigmaknight123** [comment]
Use privacy.com virtual credit cards and put a cap on them. Seems pretty easy to do.

**Comment by kkapuria3** [comment]
Read the strategy guide compiled by crazedrunner in our discord. Check out pins in #deputy-drops channel
