### ISSUE TITLE
Test check out defaulted to "Store Pick up"

### ISSUE THREAD

**Issue by gravityz3r0** [kkapuria3/BestBuy-GPU-Bot#35]
Any way to change the delivery method to "Shipping" during check out? If left untouched, the bot might just check out using the "Store Pick Up" option as the default which is undesirable. Thanks!

**Comment by The-Sickness** [comment]
I agree 100% on changing the delivery method to shipping automatically.

**Comment by kkapuria3** [comment]
I don't think they let you change it on these high demand items. 

[![Discord](https://img.shields.io/discord/863863008329596968?color=%237289da%20&label=FOR%20SUPPORT%20AND%20FAQs%20%20%7C%20JOIN%20DISCORD&style=for-the-badge)](https://discord.gg/wkznBbgBFD)
