### ISSUE TITLE
Bestbuy prompts to login before checking out process finishes this stops the bot 

### ISSUE THREAD

**Issue by canelodirrcto** [kkapuria3/BestBuy-GPU-Bot#39]
Even after selecting stay sign in on the device, once the robot has been running for a while the site will ask you to sign in again before finishing checkout process which stops the bot from completing the purchase.

Just wondering if there is a work around Thank you

**Comment by kkapuria3** [comment]
**Try this in Firefox:** 

> Open 1-8 temporary container tabs and ***stay logged out*** . Each tab will give you a separate queue time for a product you're trying to buy. Open the same product on each of your container tabs and run the script. Strategy is to only go for one item at a time. The less tabs the lower the risk of verify loops, but the more tabs the better the odds of a good queue time. If verify loops happen, close all tabs, restart firefox, create new temporary container tabs and try again.

[![Discord](https://img.shields.io/discord/863863008329596968?color=%237289da%20&label=FOR%20SUPPORT%20AND%20FAQs%20%20%7C%20JOIN%20DISCORD&style=for-the-badge)](https://discord.gg/wkznBbgBFD)
