### ISSUE TITLE
Window.Open not triggering

### ISSUE THREAD

**Issue by NPC-NPC-NPC** [kkapuria3/BestBuy-GPU-Bot#41]
I was not able to determine why, but window.open is not working for me.  It never opens a new window/tab and then when window.close fires, the process ends.

I resolved this locally by adding the following instead of window.open

// @grant    GM_openInTab
                     
GM_openInTab (window.location.href);

This seems to also protect against the mentioned memory leak.

**Comment by rdespoiu** [comment]
Regarding the `window.open` not triggering on your end, it's possible your browser is just blocking that action. I found your issue post when I experienced this myself.

I removed the `window.close()` call and Chrome prompted me to allow/block `window.open` from executing on the Best Buy website. After I clicked `allow`, I had no more issues. Just wanted to leave this here in case anyone else runs into this, as the call to `window.close()` suppresses the browser notification.

**Comment by kkapuria3** [comment]
Have you turned on pop ups for bestbuy.com ?
