### ISSUE TITLE
Window/Tab closes after page refresh

### ISSUE THREAD

**Issue by corneliusmixon** [kkapuria3/BestBuy-GPU-Bot#48]
Window/Tab closes after page refresh. I have tried on Chrome and Firefox.

**Comment by Peter-D-Finch** [comment]
I had this same issue. For me, the issue stopped after allowing pop-ups on the page.
See https://support.google.com/chrome/answer/95472?hl=en&co=GENIE.Platform%3DDesktop for instructions.

**Comment by kkapuria3** [comment]
#25
