### ISSUE TITLE
where i can find another button?

### ISSUE THREAD

**Issue by vadimka04** [kkapuria3/BestBuy-GPU-Bot#51]
I try rewrite that bot for another store. I compare buttons on bestbuy and in source code for change them for another store.
1. Where i can find that buttons?
`         const OOSButton_L2 = "btn btn-disabled btn-lg btn-block add-to-cart-button"`
i find only that button
`         const OOSButton_L1 = "c-button c-button-disabled c-button-lg c-button-block add-to-cart-button"`
![image](https://user-images.githubusercontent.com/12530745/151812800-c0456c6e-6167-460a-81be-d32e9bba01d7.png)

**Comment by kkapuria3** [comment]
Buttons are layered.. That means whenever BB will add new button classes we store them under different variables and check all of them before moving to next step.

```
OOSButton_L1 = button name in 2021 
OSSButton_L2 = button name in 2022 ..

```
point is, it should work with both the button classes if BB were to change their button classes overnight..

**Comment by vadimka04** [comment]
Thank you
