### ISSUE TITLE
How can I change the refresh rate?

### ISSUE THREAD

**Issue by Active589** [kkapuria3/BestBuy-GPU-Bot#9]
Is there a way to make it refresh faster (ex: 2 seconds)?

Or is there a reason that it cant go faster.

**Comment by kkapuria3** [comment]
![image](https://user-images.githubusercontent.com/25559534/128284758-3fa793a5-c1d8-42f5-b383-05a786efaa91.png)
Value on line 346 controls how often the page will refresh if OUT OF STOCK button is found.  Change this to 2000.
